//clean definitions
#undef NAME_EIGEN
#undef NAME_EIGEN_ALLTYPES
#undef NAME_EIGEN_ALLTYPES_BASIC
#undef NAME_EIGEN_ROWCOL_ALLTYPES
#undef NAME_EIGEN_MAT_ALLTYPES
#undef NAME_EIGEN_ROWCOL_ALLTYPES_SPECIALSIZE
#undef NAME_EIGEN_MAT_ALLTYPES_SPECIALSIZE_ROW
#undef NAME_EIGEN_MAT_ALLTYPES_SPECIALSIZE
#undef NAME_EIGEN_SPECIAL_ALLTYPES_SPECIALSIZE

#undef NO_CONFLICT
#undef FIXED_ONLY
#undef NON_FIXED_ONLY
