#LIBRARIES
#QUADMATH
FIND_PACKAGE(QUADMATH QUIET)
IF(QUADMATH_FOUND)
  LIST(APPEND ALL_LIBRARIES ${QUADMATH_LIBRARIES})
  MESSAGE(STATUS "Found QUADMATH @ ${QUADMATH_LIBRARIES}")
  IF(USE_QUADMATH)
    ADD_DEFINITIONS(-DQUADMATH_SUPPORT)
  ENDIF()
  ADD_DEFINITIONS(-DFOUND_QUADMATH)
ELSE(QUADMATH_FOUND)
  MESSAGE(WARNING "Cannot find QUADMATH, compiling without it!")
ENDIF(QUADMATH_FOUND)

#EIGEN3
IF(DEFINED ENV{EIGEN3_INCLUDE_DIR})
  MESSAGE(STATUS "Found Custom EIGEN3 @ $ENV{EIGEN3_INCLUDE_DIR}")
  INCLUDE_DIRECTORIES($ENV{EIGEN3_INCLUDE_DIR})
ELSE()
  FIND_PACKAGE(Eigen3 QUIET REQUIRED)
  IF(EIGEN3_FOUND)
    MESSAGE(STATUS "Found EIGEN3 @ ${EIGEN3_INCLUDE_DIR}")
  ELSE(EIGEN3_FOUND)
    MESSAGE(SEND_ERROR "Cannot find EIGEN3!")
  ENDIF(EIGEN3_FOUND)
  INCLUDE_DIRECTORIES(${EIGEN3_INCLUDE_DIR})
ENDIF()

#FIND GMP
FIND_PACKAGE(GMP QUIET REQUIRED)
IF(GMP_FOUND)
  MESSAGE(STATUS "Found GMP @ ${GMP_INCLUDES}")
  LIST(APPEND ALL_LIBRARIES ${GMP_LIBRARIES})
ELSEIF(GMP_FOUND)
  MESSAGE(SEND_ERROR "Cannot find GMP!")
ENDIF(GMP_FOUND)

#TinyXML2
FIND_PACKAGE(TINYXML2 QUIET)
IF(TINYXML2_FOUND)
  INCLUDE_DIRECTORIES(${TINYXML2_INCLUDE_DIRS})
  MESSAGE(STATUS "Found TinyXML2 @ ${TINYXML2_INCLUDE_DIRS}")
  LIST(APPEND ALL_LIBRARIES ${TINYXML2_LIBRARIES})
ELSE(TINYXML2_FOUND)
  MESSAGE(SEND_ERROR "Cannot find TinyXML2!")
ENDIF(TINYXML2_FOUND)

#FIND MPFR
FIND_PACKAGE(MPFR QUIET REQUIRED)
IF(MPFR_FOUND)
  INCLUDE_DIRECTORIES("${PROJECT_SOURCE_DIR}/ThirdParty")
  INCLUDE_DIRECTORIES("${PROJECT_SOURCE_DIR}/ThirdParty/mpfr-4.0.1/include")
  MESSAGE(STATUS "Found MPFR Libraries @ ${MPFR_LIBRARIES}")
  MESSAGE(STATUS "Found MPFR @ ${MPFR_INCLUDES}")
  LIST(APPEND ALL_LIBRARIES ${MPFR_LIBRARIES})
ELSEIF(MPFR_FOUND)
  MESSAGE(SEND_ERROR "Cannot find MPFR!")
ENDIF(MPFR_FOUND)

