#MOSEK
SET(SUPPORT_MOSEK ON)
IF(EXISTS "/home/$ENV{USER}/mosek/9.1/tools/platform/linux64x86")
  SET(MOSEK_ROOT "/home/$ENV{USER}/mosek/9.1/tools/platform/linux64x86")
  MESSAGE(STATUS "Using mosek 9.1!")
  ADD_DEFINITIONS(-DUSE_MOSEK_9)
ELSEIF(EXISTS "/home/$ENV{USER}/mosek/9.0/tools/platform/linux64x86")
  SET(MOSEK_ROOT "/home/$ENV{USER}/mosek/9.0/tools/platform/linux64x86")
  MESSAGE(STATUS "Using mosek 9.0!")
  ADD_DEFINITIONS(-DUSE_MOSEK_9)
ELSEIF(EXISTS "$/home/$ENV{USER}/mosek/8/tools/platform/linux64x86")
  SET(MOSEK_ROOT "/home/$ENV{USER}/mosek/8/tools/platform/linux64x86")
  MESSAGE(STATUS "Using mosek 8.0!")
  ADD_DEFINITIONS(-DUSE_MOSEK_8)
ELSEIF(EXISTS "/nas/longleaf/apps/mosek/8.0.0.53/mosek/8/tools/platform/linux64x86")
  SET(MOSEK_ROOT "/nas/longleaf/apps/mosek/8.0.0.53/mosek/8/tools/platform/linux64x86")
  MESSAGE(STATUS "Using mosek 8.0!")
  ADD_DEFINITIONS(-DUSE_MOSEK_8)
ELSE()
  MESSAGE(WARNING "Cannot find Mosek, compiling without it!")
  SET(SUPPORT_MOSEK OFF)
ENDIF()
IF(${SUPPORT_MOSEK})
  LIST(APPEND ALL_LIBRARIES "${MOSEK_ROOT}/bin/libmosek64.so")
  INCLUDE_DIRECTORIES("${MOSEK_ROOT}/src/fusion_cxx")
  INCLUDE_DIRECTORIES("${MOSEK_ROOT}/h")
  FILE(GLOB_RECURSE headerFusion ${MOSEK_ROOT}/src/fusion_cxx/*.h ${MOSEK_ROOT}/src/fusion_cxx/*.hpp ${MOSEK_ROOT}/src/fusion_cxx/*.hh)
  FILE(GLOB_RECURSE sourceFusion ${MOSEK_ROOT}/src/fusion_cxx/*.cpp ${MOSEK_ROOT}/src/fusion_cxx/*.cpp ${MOSEK_ROOT}/src/fusion_cxx/*.cc)
ENDIF()
