#FIND COMMON_FILE INCLUDE
UNSET(CommonFile_INCLUDE_DIRS CACHE)
SET(CommonFile_INCLUDE_DIRS "${PROJECT_SOURCE_DIR}/../commonfile")
IF(NOT EXISTS ${CommonFile_INCLUDE_DIRS})
  MESSAGE(SEND_ERROR "Cannot find commonfile source @ ${CommonFile_INCLUDE_DIRS}")
ENDIF()

#CHOOSE COMMON_FILE LIBRARY
IF(USE_QUADMATH)
  MESSAGE(STATUS "Using Quad Precision!")
  ADD_DEFINITIONS(-DUSE_QUADMATH)
ELSEIF(DOUBLE_PRECISION)
  MESSAGE(STATUS "Using Double Precision!")
  ADD_DEFINITIONS(-DDOUBLE_PRECISION)
ELSE()
  MESSAGE(STATUS "Using Single Precision!")
ENDIF()

#FIND_POSTFIX
UNSET(CommonFile_LIBRARY_DIR CACHE)
IF(USE_QUADMATH)
  SET(CommonFile_LIBRARY_DIR "${CommonFile_INCLUDE_DIRS}-build/${CMAKE_BUILD_TYPE}Q")
ELSEIF(DOUBLE_PRECISION)
  SET(CommonFile_LIBRARY_DIR "${CommonFile_INCLUDE_DIRS}-build/${CMAKE_BUILD_TYPE}D")
ELSE()
  SET(CommonFile_LIBRARY_DIR "${CommonFile_INCLUDE_DIRS}-build/${CMAKE_BUILD_TYPE}F")
ENDIF()

#LINK
UNSET(CommonFile_shared_LIBRARIES CACHE)
UNSET(CommonFile_static_LIBRARIES CACHE)
FIND_LIBRARY(CommonFile_shared_LIBRARIES NAMES CommonFile_shared PATHS ${CommonFile_LIBRARY_DIR} ${CommonFile_LIBRARY_DIR}/Debug ${CommonFile_LIBRARY_DIR}/Release NO_DEFAULT_PATH)
FIND_LIBRARY(CommonFile_static_LIBRARIES NAMES CommonFile_static PATHS ${CommonFile_LIBRARY_DIR} ${CommonFile_LIBRARY_DIR}/Debug ${CommonFile_LIBRARY_DIR}/Release NO_DEFAULT_PATH)

#CommonFile_FOUND
SET(CommonFile_FOUND "NO")
IF(MSVC)
  IF(CommonFile_INCLUDE_DIRS AND CommonFile_static_LIBRARIES)
    SET(CommonFile_FOUND "YES")
  ENDIF()
ELSE(MSVC)
  IF(CommonFile_INCLUDE_DIRS AND CommonFile_shared_LIBRARIES AND CommonFile_static_LIBRARIES)
    SET(CommonFile_FOUND "YES")
  ENDIF()
ENDIF(MSVC)
