#iterate over sub-directories
MACRO(SUBDIRLIST result curdir)
  FILE(GLOB children RELATIVE ${curdir} ${curdir}/*)
  SET(dirlist "")
  FOREACH(child ${children})
    IF(IS_DIRECTORY ${curdir}/${child})
      LIST(APPEND dirlist ${child})
    ENDIF()
  ENDFOREACH()
  SET(${result} ${dirlist})
ENDMACRO()

#find knitro path
SUBDIRLIST(dirs "/home/$ENV{USER}")
FOREACH(file ${children})
  STRING(REGEX MATCH "knitro-[1-9]+.[0-9]+.[0-9]+-Linux-64" KNITRO_PATH "${file}")
  IF("${KNITRO_PATH}" STREQUAL "")
  ELSE()
    SET(KNITRO_ROOT "/home/$ENV{USER}/${KNITRO_PATH}")
    LINK_DIRECTORIES(${KNITRO_ROOT}/lib)
    LIST(APPEND ALL_LIBRARIES libknitro${KTR_RELEASE}.so gfortran)
  ENDIF()
ENDFOREACH()

#check if we have knitro
IF("${KNITRO_ROOT}" STREQUAL "")
  MESSAGE(WARNING "Cannot find Knitro, compiling without it!")
ELSE()
  ADD_DEFINITIONS(-DKNITRO_SUPPORT)
  MESSAGE(STATUS "Found knitro @ ${KNITRO_ROOT}!")
  FILE(GLOB_RECURSE sourceKnitro ${KNITRO_ROOT}/examples/C++/src/*.cpp)
  INCLUDE_DIRECTORIES(${KNITRO_ROOT}/examples/C++/include)
  INCLUDE_DIRECTORIES(${KNITRO_ROOT}/include)
ENDIF()
