#Coin-HSL
IF(NOT EXISTS ${PROJECT_BINARY_DIR}/HSL-build)
  SET(HSL_ROOT "Ipopt-3.12.11/ThirdParty/HSL")
  EXECUTE_PROCESS(COMMAND mkdir HSL-build WORKING_DIRECTORY ${PROJECT_BINARY_DIR})
  EXECUTE_PROCESS(COMMAND bash ${PROJECT_SOURCE_DIR}/ThirdParty/${HSL_ROOT}/configure
                  --prefix=${PROJECT_BINARY_DIR}/HSL-build --enable-debug=yes --enable-shared=no --with-pic=yes
                  WORKING_DIRECTORY ${PROJECT_BINARY_DIR}/HSL-build)
  EXECUTE_PROCESS(COMMAND make install WORKING_DIRECTORY ${PROJECT_BINARY_DIR}/HSL-build)
ENDIF()
FIND_LIBRARY(COINHSL_LIBRARY NAMES coinhsl libcoinhsl PATHS
             ${PROJECT_BINARY_DIR}/HSL-build/lib NO_DEFAULT_PATH)
IF(COINHSL_LIBRARY)
  MESSAGE(STATUS "Found Coin-HSL Libraries @ ${COINHSL_LIBRARY}")
  LIST(APPEND ALL_LIBRARIES ${COINHSL_LIBRARY})
ELSE()
  MESSAGE(SEND_ERROR "Cannot find Coin-HSL!")
ENDIF()
